name: Verify project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python Requirements
        run: pipenv install --ignore-pipfile

      - name: Run Tests
        run: |
          pipenv run pytest main.py -v --junitxml="result.xml"

      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: "Unit test report"
          path: 'result.xml'
          reporter: java-junit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: result.xml